name: Autograding Tests

on:
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run pytest
        id: run-tests
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: python
          args: -m pytest -q
          setup-command: ""
          timeout: 20

      - name: Autograding Test Runner
        id: tests
        uses: classroom-resources/autograding-test-runner@v1
        with:
          test_suite: |
            - name: summarize_adoptions tests
              setup: ""
              run: python -m pytest -q
              points: 100

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TESTS_RESULTS: "${{ steps.tests.outputs.result }}"
        with:
          runners: tests
